export const MENTOR_LIST_REQUEST = "MENTOR_LIST_REQUEST";
export const MENTOR_LIST_SUCCESS = "MENTOR_LIST_SUCCESS";
export const MENTOR_LIST_FAIL = "MENTOR_LIST_FAIL";

export const MENTOR_DETAILS_REQUEST = "MENTOR_DETAILS_REQUEST";
export const MENTOR_DETAILS_SUCCESS = "MENTOR_DETAILS_SUCCESS";
export const MENTOR_DETAILS_FAIL = "MENTOR_DETAILS_FAIL";

export const STUDENTS_OF_MENTOR_REQUEST = "STUDENTS_OF_MENTOR_REQUEST";
export const STUDENTS_OF_MENTOR_SUCCESS = "STUDENTS_OF_MENTOR_SUCCESS";
export const STUDENTS_OF_MENTOR_FAIL = "STUDENTS_OF_MENTOR_FAIL";

export const MENTOR_ADD_TIMESLOTS_REQUEST = "MENTOR_ADD_TIMESLOTS_REQUEST";
export const MENTOR_ADD_TIMESLOTS_SUCCESS = "MENTOR_ADD_TIMESLOTS_SUCCESS";
export const MENTOR_ADD_TIMESLOTS_FAIL = "MENTOR_ADD_TIMESLOTS_FAIL";
